[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
window = { git = "https://github.com/Slazaa/Rust-Window" }
gl = "0.14.0"

[target.'cfg(windows)'.dependencies.winapi]
winapi = "0.3.9"